default:
  image: docker:latest
  before_script:
    - apk add make
  services:
    - docker:dind
  tags:
    - docker
    - gpu

stages:
  - test
  - push

test_cuda11_0:
  stage: test
  script:
    - make -C cuda11_0 test

test_cuda10_2:
  stage: test
  script:
    - make -C cuda10_2 test

docker:
  stage: push
  script:
    - make push
