default:
  image: docker:latest
  before_script:
    - apk add coreutils git make
  services:
    - docker:dind

stages:
  - build
  - test
  - push

gcc-cuda:
  stage: build
  script:
    - make test
  tags:
    - docker
    - gpu

clang11gcc7-cuda10_1-mkl-build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - make -C clang11gcc7/cuda10_1/mkl build
    - make -C clang11gcc7/cuda10_1/mkl push
  timeout: 3 hours
  tags:
    - docker
    - cpu-ge-8
    - mem-ge-32gb

clang11gcc7-cuda10_1-mkl-test:
  stage: test
  image: ${CI_REGISTRY_IMAGE}/clang11gcc7/cuda10_1/mkl:${CI_COMMIT_REF_NAME}
  script:
    - ls /examples
  tags:
    - gpu

push:
  stage: push
  script:
    - docker login -u termoshtt -p ${GITHUB_PACKAGE_TOKEN_TERMOSHTT} ghcr.io/ricosjp
    - make push
    - make -C clang11gcc7/cuda10_1/mkl push
  timeout: 3 hours
  tags:
    - docker
    - cpu-ge-8
    - mem-ge-32gb
