default:
  image: docker:latest
  before_script:
    - apk add coreutils git make
  services:
    - docker:dind
  tags:
    - docker
    - gpu

stages:
  - test
  - push

test:
  stage: test
  script:
    - make test

clang11gcc7-cuda10_1-mkl:
  stage: test
  script:
    - make -C clang11gcc7/cuda10_1/mkl build
  timeout: 3 hours

push:
  stage: push
  script:
    - docker login -u termoshtt -p ${GITHUB_PACKAGE_TOKEN_TERMOSHTT} ghcr.io/ricosjp
    - make push
    - make -C clang11gcc7/cuda10_1/mkl push
