.dind:
  image: docker:latest
  before_script:
    - apk add coreutils git make
  services:
    - docker:dind

stages:
  - build
  - test
  - deploy

build-cuda11_4-clang12:
  extends: .dind
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - make push/cuda11_4/clang12/mkl
    - make push/cuda11_4/clang12/oss
  timeout: 3 hours
  tags:
    - docker
    - cpu-ge-8
    - mem-ge-32gb

build-cuda11_4-clang13:
  extends: .dind
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - make push/cuda11_4/clang13/mkl
    - make push/cuda11_4/clang13/oss
  timeout: 3 hours
  tags:
    - docker
    - cpu-ge-8
    - mem-ge-32gb

build-cuda11_4-gcc10:
  extends: .dind
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - make push/cuda11_4/gcc10/mkl
    - make push/cuda11_4/gcc10/oss
  tags:
    - docker

build-clang-format:
  extends: .dind
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - make push/clang-format
  tags:
    - docker

build-doxygen:
  extends: .dind
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - make push/doxygen
  tags:
    - docker

build-poetry:
  extends: .dind
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - make push/poetry
  tags:
    - docker

release:
  extends: .dind
  stage: deploy
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker login -u termoshtt -p ${GITHUB_PACKAGE_TOKEN_TERMOSHTT} ghcr.io/ricosjp
    - make release
  tags:
    - docker
  only:
    - latest
    - tags

cuda11_4-clang12-mkl-test:
  stage: test
  image: ${CI_REGISTRY_IMAGE}/cuda11_4-clang12-mkl:${CI_COMMIT_REF_NAME}
  before_script:
    - nvidia-smi
  script:
    - make -C /examples/clang_omp_offloading test
    - make -C /examples/mpi_clang_omp_offloading test
  tags:
    - gpu

cuda11_4-clang12-oss-test:
  stage: test
  image: ${CI_REGISTRY_IMAGE}/cuda11_4-clang12-oss:${CI_COMMIT_REF_NAME}
  before_script:
    - nvidia-smi
  script:
    - make -C /examples/clang_omp_offloading test
    - make -C /examples/mpi_clang_omp_offloading test
  tags:
    - gpu

cuda11_4-clang13-mkl-test:
  stage: test
  image: ${CI_REGISTRY_IMAGE}/cuda11_4-clang13-mkl:${CI_COMMIT_REF_NAME}
  before_script:
    - nvidia-smi
  script:
    - make -C /examples/clang_omp_offloading test
    - make -C /examples/mpi_clang_omp_offloading test
  tags:
    - gpu

cuda11_4-clang13-oss-test:
  stage: test
  image: ${CI_REGISTRY_IMAGE}/cuda11_4-clang13-oss:${CI_COMMIT_REF_NAME}
  before_script:
    - nvidia-smi
  script:
    - make -C /examples/clang_omp_offloading test
    - make -C /examples/mpi_clang_omp_offloading test
  tags:
    - gpu

cuda11_4-gcc10-oss-test:
  stage: test
  image: ${CI_REGISTRY_IMAGE}/cuda11_4-gcc10-oss:${CI_COMMIT_REF_NAME}
  before_script:
    - nvidia-smi
  script:
    - make -C /examples/gcc_omp_offloading test
    - make -C /examples/gcc_openacc test
    - make -C /examples/gfortran_omp_offloading test
    - make -C /examples/gfortran_openacc test
  tags:
    - gpu

cuda11_4-gcc10-mkl-test:
  stage: test
  image: ${CI_REGISTRY_IMAGE}/cuda11_4-gcc10-oss:${CI_COMMIT_REF_NAME}
  before_script:
    - nvidia-smi
  script:
    - make -C /examples/gcc_omp_offloading test
    - make -C /examples/gcc_openacc test
    - make -C /examples/gfortran_omp_offloading test
    - make -C /examples/gfortran_openacc test
  tags:
    - gpu

clang-format-version:
  stage: test
  image: ${CI_REGISTRY_IMAGE}/clang-format:${CI_COMMIT_REF_NAME}
  script:
    - clang-format --version

doxygen-version:
  stage: test
  image: ${CI_REGISTRY_IMAGE}/doxygen:${CI_COMMIT_REF_NAME}
  script:
    - doxygen --version

poetry-version:
  stage: test
  image: ${CI_REGISTRY_IMAGE}/poetry:${CI_COMMIT_REF_NAME}
  script:
    - poetry --version

keep-changelog:
  image: alpine:latest
  stage: build
  before_script:
    - apk add git
  script:
    - git fetch
    - "! git diff --exit-code origin/latest CHANGELOG.md"
  allow_failure: true
  except:
    - latest
    - tags

clang_format:
    image: ghcr.io/ricosjp/allgebra/clang-format:20.10.1
    stage: build
    script:
      - check-format.sh
    allow_failure: true
