.dind:
  image: docker:latest
  before_script:
    - apk add coreutils git make
  services:
    - docker:dind

stages:
  - build
  - test
  - push

gcc-cuda:
  extends: .dind
  stage: build
  script:
    - make test
  tags:
    - docker
    - gpu

cuda10_1-clang11gcc7:
  extends: .dind
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - make -f clang11gcc7.mk push
  timeout: 3 hours
  tags:
    - docker
    - cpu-ge-8
    - mem-ge-32gb

cuda10_1-clang11gcc7-release:
  extends: .dind
  needs:
    - cuda10_1-clang11gcc7
  stage: deploy
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker login -u termoshtt -p ${GITHUB_PACKAGE_TOKEN_TERMOSHTT} ghcr.io/ricosjp
    - make -f clang11gcc7.mk release
  tags:
    - docker
  only:
    - latest
    - tags

cuda10_1-clang11gcc7-mkl-test:
  stage: test
  needs:
    - cuda10_1-clang11gcc7
  image: ${CI_REGISTRY_IMAGE}/cuda10_1-clang11gcc7-mkl:${CI_COMMIT_REF_NAME}
  before_script:
    - nvidia-smi
  script:
    - cd /examples/clang_omp_offloading
    - make test
  tags:
    - gpu

cuda10_1-clang11gcc7-oss-test:
  stage: test
  needs:
    - cuda10_1-clang11gcc7
  image: ${CI_REGISTRY_IMAGE}/cuda10_1-clang11gcc7-oss:${CI_COMMIT_REF_NAME}
  before_script:
    - nvidia-smi
  script:
    - cd /examples/clang_omp_offloading
    - make test
  tags:
    - gpu

keep-changelog:
  image: ghcr.io/ricosjp/allgebra/clang-format:20.10.1
  stage: build
  script:
    - git fetch
    - "! git diff --exit-code origin/latest CHANGELOG.md"
  allow_failure: true
  except:
    - latest
    - tags
