default:
  image: docker:latest
  before_script:
    - apk add make
  services:
    - docker:dind
  tags:
    - docker
    - gpu

stages:
  - test
  - push

test:
  stage: test
  script:
    - make test

push:
  stage: push
  script:
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY_IMAGE}
    - make push
