default:
  image: docker:latest
  before_script:
    - apk add coreutils git make
  services:
    - docker:dind
  tags:
    - docker
    - gpu

stages:
  - test
  - push

test:
  stage: test
  script:
    - make test

push:
  stage: push
  script:
    - docker login -u termoshtt -p ${GITHUB_PACKAGE_TOKEN_TERMOSHTT} ghcr.io/ricosjp
    - make push
